### ISSUE TITLE
Prepare for 0.2.0

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/book#24]
Updates to:

**Setup**
- [x] overhaul entirely

**Core**
- [x] set! and get! 
- [x] global macro explanations
- [x] !emit macro for custom world events
- [x] explicit component keys
- [x] explain Auth

**ERC**
- [x] erc20 / erc721 / erc1155 
- [ ] examples for each

**Torii**
- [ ] torii relay support
- [ ] flesh documentation more

**Katana**
- [x] Update to new cli commands

**Sozo**
- [x] Update to new cli commands 

**Deployment**
- [ ] Starknet
- [ ] Madara
- [x] Katana

**Packages**
Need sections for each
- [ ] @dojoengine/core
- [ ] @dojoengine/react
- [ ] @dojoengine/create-burner

**Tutorial**
- [ ] Building the dojo-starter + using the dojo-starter-react
```[tasklist]
### Tasks
```
